### ISSUE TITLE
Rustls example

### ISSUE THREAD

**Issue by jan-br** [BlackbirdHQ/rustot#40]
Hi again (probably @MathiasKoch ) :)
I was just wondering if you have by any chance a basic provisioning example with rustls instead of nativetls.
I'm still working on ESP32 and I got ring - which was a real hustle btw - and rustls to run, but not nativetls.

This is quite urgent actually. The company I am working for just got a potential task from another company to build some embedded firmware with aws connectivity. And I would love to use this crate since it is the only one, I can possibly find which I can convince to compile for the xtensa architecture. All other crates use mio in some regard, which is not implemented for esp yet. So if I can get this to work with rustls in the next 1-2 days, I would not have to build that firmware with c++ but could choose rust. Really not looking forward to build that thing with c++.

**Comment by MathiasKoch** [comment]
Unfortunately i do not have a rustls based example, but i think it should be fairly straight forward for you to swap out native-tls for rustls in the examples?
