### ISSUE TITLE
Risk: over-authorization of AWS IoT policy

### ISSUE THREAD

**Issue by P-Verifier** [BlackbirdHQ/rustot#42]
We are a security research team and we recently discovered that there is an over-authorization security issue with this project's IoT policy.
The affected file is as following:

	1. rustot/examples/provisioning_infrastructure/full_iot_policy.json

**Comment by MathiasKoch** [comment]
Thanks for highlighting this, but as that is only meant as an example for the library I will leave it like this (As does AWS in their examples).
